package TB2.NewStructure.common.Gebaeude;

public enum Buildings {
    HAUPTGEBAEUDE, HOLZFAELLER, LEHMGRUBE, EISENMINE, BAUERNHOF, SPEICHER, KIRCHE, SAMMELPLATZ, KASERNE, STATUE, LAZARETT, WALL, MARKT, TAVERNE, AKADEMIE, ORDENSHALLE, KAPELLE
}
